services:

  ssh-tunnel:
    build:
      context: ./deploy/ssh

    container_name: ssh-tunnel

    restart: always
    tty: true

    env_file:
      - .env

    volumes:
      - ./deploy/ssh/id_rsa:/tmp/id_rsa:ro

    command:
      - sh
      - -c
      - |
          mkdir -p /root/.ssh && \
          cp /tmp/id_rsa /root/.ssh/id_rsa && \
          chmod 600 /root/.ssh/id_rsa && \
          autossh \
            -M 0 \
            -N \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            -o ServerAliveCountMax=3 \
            -o ExitOnForwardFailure=yes \
            -i /root/.ssh/id_rsa \
            -p ${SSH_PORT} \
            -L 0.0.0.0:${DB_LOCAL_PORT}:${DB_REMOTE_HOST}:${DB_REMOTE_PORT} \
            ${SSH_USER}@${SSH_HOST}

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${DB_LOCAL_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .

    container_name: metricas-extractores

    env_file:
      - .env

    depends_on:
      ssh-tunnel:
        condition: service_healthy

    restart: always

    ports:
      - "8501:8501"
